Refactor GitHub Actions workflow for ROS 2 CI

diff --git a/.github/workflows/ros2_ci.yml b/.github/workflows/ros2_ci.yml
--- a/.github/workflows/ros2_ci.yml
+++ b/.github/workflows/ros2_ci.yml
@@ -1,32 +1,65 @@
-jobs:
-  ros_ci:
-    runs-on: ubuntu-22.04
+  name: build and test
 
-    strategy:
-      fail-fast: false
-      matrix:
-        ros_distro: [humble]
+  on:
+    push:
+      branches: [ main ]
+    pull_request:
+      branches: [ main ]
 
-    steps:
-      - name: ⬇️ Checkout code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
+  jobs:
+    build_and_test:
+      strategy:
+        matrix:
+          os: 
+            - ubuntu-22.04
+          rosdistro:
+            - humble
+        
+      runs-on: ${{ matrix.os }}
 
-      - name: ⚙️ Setup ROS 2
-        uses: ros-tooling/setup-ros@v0.7
-        with:
-          ros-distro: ${{ matrix.ros_distro }}
+      container:
+        image: ros:${{ matrix.rosdistro}}-ros-base
+      steps:
+        - name: Setup directories
+          run: mkdir -p ros2_ws/src
 
-      - name: 🏗️ Build, Test, and Lint ROS 2 Packages
-        uses: ros-tooling/action-ros-ci@v0.4
-        with:
-          target-ros2-distro: ${{ matrix.ros_distro }}
-          rosdep-args: --rosdistro humble --as-root apt:false --verbose
+        - name: Check out repository
+          uses: actions/checkout@v3
+          with: 
+            path: ros2_ws/src/simple_project
 
-      - name: 📦 Upload Logs
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: humble-ci-logs
-          path: log/
+        - name: Install dependencies
+          run: |
+            rosdep update &&
+            apt-get update &&
+            rosdep install --from-path . -i -y --rosdistro ${{ matrix.rosdistro}}
+
+        - name: Install diagnostic-updater
+          run: apt-get install ros-${{ matrix.rosdistro }}-diagnostic-updater
+        
+        - name: Build test
+          id: build_test
+          run: |
+            . /opt/ros/${{ matrix.rosdistro }}/setup.sh &&
+            colcon build
+          continue-on-error: true
+        
+        - name: build_test command success
+          if: steps.build_test.outcome == 'success'
+          run: echo "result - success"
+
+        - name: build_test command failure
+          if: steps.build_test.outcome == 'failure'
+          run: echo "result - failure" && exit 1
+
+        - name: Run tests
+          id: run_test
+          run: |
+            . /opt/ros/${{ matrix.rosdistro }}/setup.sh &&
+            colcon test &&
+            colcon test-result
+          continue-on-error: true
+        
+        - name: run_test command success
+          if: steps.run_test.outcome == 'failure'
+          run: echo "result -failed" && exit 1
